### ISSUE TITLE
Wiki not up-to-date

### ISSUE THREAD

**Issue by kevin-sakemaer** [duniter/website_fr#25]
the wiki on the command line interface is not up-to-date.
will add command that are in the wiki and are not working when i try them with 1.6.14

- [ ] `duniter config --ws2p-noprivate`
- [ ] `duniter gen-next --show --check`
- [ ] `duniter config --ws2p-max-private <count>`
- [ ] `duniter config --ws2p-prefered-add <pubkey>`
- [ ] `duniter ws2p list-prefered`
- [ ] `duniter config --ws2p-prefered-only`
- [ ] `duniter config --tor-proxy localhost:9050 --reaching-clear-ep tor`
- [ ] `duniter --rm-proxies`
- [ ] `duniter config --ws2p-public`
- [ ] `duniter ws2p show-conf`
- [ ] `duniter webstart`
- [ ] `duniter webrestart`

**Comment by c-geek** [comment]
cc @librelois

**Comment by librelois** [comment]
@Kleak I just re-tested my Duniter 1.6.14 just now and all its controls work fine except two :

duniter gen-next --show --check
I did not test this command.

dunter config --ws2p-prefered-only
Yes it doesn't work in ws2p 1, I remove it from the wiki.

For all other orders, however, they work well !
What makes you think they don't work at home?

**Comment by kevin-sakemaer** [comment]
all the command i have listed above give me this kind of error 
`Unknown command 'webstart'. Try --help for a listing of commands & options.`

**Comment by librelois** [comment]
@Kleak What is your operating system? Which release did you install? Is it a binary or sources?

**Comment by kevin-sakemaer** [comment]
from this link https://github.com/duniter/duniter/releases/download/v1.6.14/duniter-desktop-v1.6.14-linux-x64.deb

**Comment by kevin-sakemaer** [comment]
oops no from the source branch 1.6 sorry

**Comment by librelois** [comment]
@Kleak Ok from the sources you miss the module duniter-ui which you have to plugger manually:

    bin/duniter plug duniter-ui@1.6.x

**Comment by kevin-sakemaer** [comment]
but i use the cli i don't need the ui

**Comment by librelois** [comment]
@Kleak web-ui is needed for the `webstart` and `webrestart` commands

For the other commands they work at home from sources on branche 1.6, I think the problem comes from your environment.

**Comment by librelois** [comment]
@Kleak do you use the `bin/duniter` command instead of `duniter`?

**Comment by kevin-sakemaer** [comment]
ok.
Hm seems `bin/duniter` work and not `duniter` maybe a more explicit error can help here

**Comment by kevin-sakemaer** [comment]
another question before we close this:
i need to be a member to not be a mirror ?
![screenshot from 2017-11-17 18-08-54](https://user-images.githubusercontent.com/5434752/32959599-63d23cb6-cbc2-11e7-8650-86bc2556e871.png)

**Comment by librelois** [comment]
Yes mirror node = non-member node

**Comment by kevin-sakemaer** [comment]
ok thanks for all :) hopefully one day i will be a member

**Comment by c-geek** [comment]
Kleak: are you french? Because we have a meetup newt week: https://rml10.duniter.org/

**Comment by kevin-sakemaer** [comment]
oui pres de toulouse, il y a le [capitole du libre](https://2017.capitoledulibre.org/) demain et apres demain mais je suis pas dispo :/

**Comment by librelois** [comment]
@Kleak arf j'y serai, dommage tu va rater ma conf sur duniter :p

**Comment by kevin-sakemaer** [comment]
oui je sais :/ une prochaine foi 
Tu est de toulouse @librelois ?

**Comment by librelois** [comment]
@Kleak non Montpellier :)

**Comment by kevin-sakemaer** [comment]
oki si je passe par labas je te fais signe ^^
