### ISSUE TITLE
ultra quick fix to the french rss link

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [duniter/website_fr#26]
Hi,
on the french page : https://duniter.org/fr, I'm fairly certain that if on the right you click on "RSS" you get a 404 because the link is : 
https://duniter.org/feeds/all.atom.xml             instead of 
https://duniter.org **/fr/** feeds/all.atom.xml

**Comment by c-geek** [comment]
Yes you are right. I will try to check this ASAP ... so maybe tomorrow.

**Comment by c-geek** [comment]
Done.
